# Generated by Django 4.1.3 on 2022-11-04 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_status_order_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='status',
        ),
    ]
